name: Notion to Markdown Sync

on:
  schedule:
    - cron: "0 7 * * *" # 매일 7시 실행 (필요에 맞게 조절)
  workflow_dispatch: # 수동 실행 가능

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests markdownify notion-client

      - name: Fetch Notion content
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python notion_to_md.py

      - name: Read commit messages
        id: commit_msg
        run: |
          if [ -f commit_messages.txt ]; then
            echo "COMMIT_MSG=$(cat commit_messages.txt | tr '\n' '; ')" >> $GITHUB_ENV
          else
            echo "COMMIT_MSG=Updated blog posts" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "grapefruitgreentealoe"
          git config --global user.email "nammugmuhg@gmail.com"
          git add blog/*.md commit_messages.txt last_updated.txt 
          git commit -m "$COMMIT_MSG" || echo "No changes to commit"
          git push
